# Generated by Django 5.1.6 on 2025-04-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("description", models.TextField(verbose_name="介绍")),
                (
                    "image",
                    models.ImageField(upload_to="project_images/", verbose_name="图片"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="是否展示"),
                ),
            ],
        ),
    ]
