# Generated by Django 5.1.6 on 2025-03-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
            ],
        ),
    ]
